# Generated by Django 5.0.6 on 2024-06-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gest_prueba', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedades',
            name='tratamientos',
            field=models.ManyToManyField(blank=True, null=True, related_name='enfermedad_tratamiento', to='gest_prueba.tratamientos'),
        ),
    ]
